<?php

/* DEFAULT OPTIONS */

$tb_customize_colors = array(
	array( 'slug'=>'tb_primary_color', 'default' => '#dd0000', 'label' => __( 'Primary Theme Color', 'themeboy' ) ),
	array( 'slug'=>'tb_secondary_color', 'default' => '#ffffff', 'label' => __( 'Secondary Theme Color', 'themeboy' ) ),
	array( 'slug'=>'tb_tagline_textcolor', 'default' => '#dd0000', 'label' => __( 'Tagline Color', 'themeboy' ) ),
	array( 'slug'=>'tb_menu_textcolor', 'default' => '#dddddd', 'label' => __( 'Menu Text Color', 'themeboy' ) ),
	array( 'slug'=>'tb_menu_bgcolor', 'default' => '#333333', 'label' => __( 'Menu Background Color', 'themeboy' ) ),
	array( 'slug'=>'tb_rotator_textcolor', 'default' => '#333333', 'label' => __( 'Image Rotator Text Color', 'themeboy' ) ),
	array( 'slug'=>'tb_rotator_bgcolor', 'default' => '#f5f5f5', 'label' => __( 'Image Rotator Background Color', 'themeboy' ) ),
	array( 'slug'=>'tb_content_textcolor', 'default' => '#333333', 'label' => __( 'Content Text Color', 'themeboy' ) ),
	array( 'slug'=>'tb_content_bgcolor', 'default' => '#ffffff', 'label' => __( 'Content Background Color', 'themeboy' ) ),
	array( 'slug'=>'tb_sidebar_bgcolor', 'default' => '#f0f0f0', 'label' => __( 'Sidebar Background Color', 'themeboy' ) ),
	array( 'slug'=>'tb_widget_bgcolor', 'default' => '#ffffff', 'label' => __( 'Widget Background Color', 'themeboy' ) ),
	array( 'slug'=>'tb_sponsors_bgcolor', 'default' => '#f0f0f0', 'label' => __( 'Sponsors Background Color', 'themeboy' ) ),
	array( 'slug'=>'tb_footer_bgcolor', 'default' => '#333333', 'label' => __( 'Footer Background Color', 'themeboy' ) )
);

$tb_customize_header_images = array(
	array( 'slug'=>'tb_header_logo_image', 'default' => get_bloginfo('template_directory').'/images/logo.png', 'label' => __( 'Header Logo Image', 'themeboy' ) ),
	array( 'slug'=>'tb_footer_logo_image', 'default' => get_bloginfo('template_directory').'/images/footer-logo.png', 'label' => __( 'Footer Logo Image', 'themeboy' ) ),
	array( 'slug'=>'tb_favicon_image', 'default' => get_bloginfo('template_directory').'/images/favicon.ico', 'label' => __( 'Shortcut Icon Image', 'themeboy' ) )
);

$tb_option_fields = array(
	'settings' => array(
		'tb_header_sponsor' => 0,
		'tb_header_sponsor_2' => 0,
		'tb_region_code' => 'au',
		'tb_default_club' => null,
		'tb_matches_hide_default_club' => 0,
		'tb_footer_show_sponsors' => 1,
		'tb_responsive' => 1
	),
	'social' => array(
		'tb_social_facebook' => 'http://facebook.com/themeboy',
		'tb_social_show_facebook_like_button' => 1,
		'tb_social_twitter' => 'http://twitter.com/themeboy',
		'tb_social_twitter_via' => 'themeboy',
		'tb_social_twitter_hashtags' => '',
		'tb_social_show_twitter_tweet_button' => 1,
		'tb_social_pinterest' => 'http://pinterest.com/themeboy',
		'tb_social_linkedin' => 'http://linkedin.com/company/themeboy',
		'tb_social_gplus' => 'http://gplus.to/themeboy',
		'tb_social_youtube' => 'http://youtube.com/themeboychannel',
		'tb_social_vimeo' => 'http://vimeo.com/themeboy'
	),
	'rotator' => array(
		'tb_rotator_cat' => 0,
		'tb_rotator_delay_in_seconds' => 4,
		'tb_rotator_show_date' => 1,
		'tb_rotator_show_readmore' => 1
	),
	'team' => array(
		'tb_players_view' => 'list',
		'tb_player_gallery_show_name' => 1,
		'tb_player_gallery_show_number' => 1,
		'tb_player_profile_show_number' => 1,
		'tb_player_profile_show_name' => 1,
		'tb_player_profile_show_dob' => 1,
		'tb_player_profile_show_age' => 1,
		'tb_player_profile_show_season' => 1,
		'tb_player_profile_show_team' => 1,
		'tb_player_profile_show_position' => 1,
		'tb_player_profile_show_appearances' => 1,
		'tb_player_profile_show_goals' => 1,
		'tb_player_profile_show_assists' => 1,
		'tb_player_profile_show_joined' => 1,
		'tb_player_profile_show_hometown' => 1,
		'tb_staff_profile_show_dob' => 1,
		'tb_staff_profile_show_age' => 1,
		'tb_staff_profile_show_natl' => 1,
		'tb_staff_profile_show_seasons' => 1,
		'tb_staff_profile_show_teams' => 1
	),
	'standings' => array(
		'tb_standings_win_points' => '3',
		'tb_standings_draw_points' => '1',
		'tb_standings_loss_points' => '0',
		'tb_standings_pos_label' => __( 'Pos', 'themeboy' ),
		'tb_standings_p_label' => __( 'P', 'themeboy' ),
		'tb_standings_w_label' => __( 'W', 'themeboy' ),
		'tb_standings_d_label' => __( 'D', 'themeboy' ),
		'tb_standings_l_label' => __( 'L', 'themeboy' ),
		'tb_standings_f_label' => __( 'F', 'themeboy' ),
		'tb_standings_a_label' => __( 'A', 'themeboy' ),
		'tb_standings_gd_label' => __( 'GD', 'themeboy' ),
		'tb_standings_pts_label' => __( 'Pts', 'themeboy' )
	),
	'matches' => array(
		'tb_match_home_title_format' => '%home% vs %away%',
		'tb_match_away_title_format' => '%home% vs %away%'
	),
	'contact' => array(
		'tb_contact_title' => __('Contact Form', 'themeboy'),
		'tb_contact_email' => get_option('admin_email'),
		'tb_contact_thanks_text' => __('Thanks, your email was sent successfully.', 'themeboy'),
		'tb_contact_error_text' => __('Oops! There was a problem sending your message. Please fix the errors below.', 'themeboy'),
		'tb_contact_thanks_subject' => __('Thank you for your message', 'themeboy'),
		'tb_contact_thanks_email' => __('Our team will be in touch with you shortly.', 'themeboy')
	),
	'customize' => array(
		'tb_primary_color' => '#dd0000',
		'tb_header_logo_image' => get_bloginfo('template_directory') . '/images/logo.png',
		'tb_footer_logo_image' => get_bloginfo('template_directory') . '/images/footer-logo.png',
		'tb_favicon_image' => get_bloginfo('template_directory').'/images/favicon.ico'
	),
	'advanced' => array(
		'tb_custom_css' => '',
		'tb_custom_scripts' => '<script type="text/javascript">' . "\r\n" . '</script>',
		'tb_title_delimiter' => '-',
		'tb_match_goals_delimiter' => '-'
	)
);

/* ORDER OPTIONS */
$tb_order_options = array(
	'ASC' => __( 'Lowest to highest', 'themeboy' ),
	'DESC' => __( 'Highest to lowest', 'themeboy' )
);

/* ORDER OPTIONS */
$tb_players_view_types = array(
	'list' => __( 'List', 'themeboy' ),
	'gallery' => __( 'Gallery', 'themeboy' )
);

/* LEAGUE TABLE STATISTCS */
$tb_standings_stats_labels = array(
	'p' => get_option( 'tb_standings_p_label' ),
	'w' => get_option( 'tb_standings_w_label' ),
	'd' => get_option( 'tb_standings_d_label' ),
	'l' => get_option( 'tb_standings_l_label' ),
	'f' => get_option( 'tb_standings_f_label' ),
	'a' => get_option( 'tb_standings_a_label' ),
	'gd' => get_option( 'tb_standings_gd_label' ),
	'pts' => get_option( 'tb_standings_pts_label' )
);

/* MATCH PLAYER STATISTCS */
$tb_player_stats_labels = array(
	'goals' => __( 'Goals', 'themeboy' ),
	'assists' => __( 'Assists', 'themeboy' ),
	'yellowcards' => __( 'Yellow Cards', 'themeboy' ),
	'redcards' => __( 'Red Cards', 'themeboy' )
);

/* LIST OF COUNTRIES */
$tb_countries_of_the_world = array(
	'ad' => 'AD',
	'ae' => 'AE',
	'af' => 'AF',
	'ag' => 'AG',
	'ai' => 'AI',
	'al' => 'AL',
	'am' => 'AM',
	'an' => 'AN',
	'ao' => 'AO',
	'aq' => 'AQ',
	'ar' => 'AR',
	'as' => 'AS',
	'at' => 'AT',
	'au' => 'AU',
	'aw' => 'AW',
	'ax' => 'AX',
	'az' => 'AZ',
	'ba' => 'BA',
	'bb' => 'BB',
	'bd' => 'BD',
	'be' => 'BE',
	'bf' => 'BF',
	'bg' => 'BG',
	'bh' => 'BH',
	'bi' => 'BI',
	'bj' => 'BJ',
	'bm' => 'BM',
	'bn' => 'BN',
	'bo' => 'BO',
	'br' => 'BR',
	'bs' => 'BS',
	'bt' => 'BT',
	'bv' => 'BV',
	'bw' => 'BW',
	'by' => 'BY',
	'bz' => 'BZ',
	'ca' => 'CA',
	'cc' => 'CC',
	'cd' => 'CD',
	'cf' => 'CF',
	'cg' => 'CG',
	'ch' => 'CH',
	'ci' => 'CI',
	'ck' => 'CK',
	'cl' => 'CL',
	'cm' => 'CM',
	'cn' => 'CN',
	'co' => 'CO',
	'cr' => 'CR',
	'cs' => 'CS',
	'ct' => 'CT',
	'cu' => 'CU',
	'cv' => 'CV',
	'cx' => 'CX',
	'cy' => 'CY',
	'cz' => 'CZ',
	'de' => 'DE',
	'dj' => 'DJ',
	'dk' => 'DK',
	'dm' => 'DM',
	'do' => 'DO',
	'dz' => 'DZ',
	'ec' => 'EC',
	'ee' => 'EE',
	'eg' => 'EG',
	'eh' => 'EH',
	'en' => 'EN',
	'er' => 'ER',
	'es' => 'ES',
	'et' => 'ET',
	'fi' => 'FI',
	'fj' => 'FJ',
	'fk' => 'FK',
	'fm' => 'FM',
	'fo' => 'FO',
	'fr' => 'FR',
	'ga' => 'GA',
	'gb' => 'GB',
	'gd' => 'GD',
	'ge' => 'GE',
	'gf' => 'GF',
	'gg' => 'GG',
	'gh' => 'GH',
	'gi' => 'GI',
	'gl' => 'GL',
	'gm' => 'GM',
	'gn' => 'GN',
	'gp' => 'GP',
	'gq' => 'GQ',
	'gr' => 'GR',
	'gs' => 'GS',
	'gt' => 'GT',
	'gu' => 'GU',
	'gw' => 'GW',
	'gy' => 'GY',
	'hk' => 'HK',
	'hm' => 'HM',
	'hn' => 'HN',
	'hr' => 'HR',
	'ht' => 'HT',
	'hu' => 'HU',
	'id' => 'ID',
	'ie' => 'IE',
	'il' => 'IL',
	'im' => 'IM',
	'in' => 'IN',
	'io' => 'IO',
	'iq' => 'IQ',
	'ir' => 'IR',
	'is' => 'IS',
	'it' => 'IT',
	'je' => 'JE',
	'jm' => 'JM',
	'jo' => 'JO',
	'jp' => 'JP',
	'ke' => 'KE',
	'kg' => 'KG',
	'kh' => 'KH',
	'ki' => 'KI',
	'km' => 'KM',
	'kn' => 'KN',
	'kp' => 'KP',
	'kr' => 'KR',
	'kw' => 'KW',
	'ky' => 'KY',
	'kz' => 'KZ',
	'la' => 'LA',
	'lb' => 'LB',
	'lc' => 'LC',
	'li' => 'LI',
	'lk' => 'LK',
	'lr' => 'LR',
	'ls' => 'LS',
	'lt' => 'LT',
	'lu' => 'LU',
	'lv' => 'LV',
	'ly' => 'LY',
	'ma' => 'MA',
	'mc' => 'MC',
	'md' => 'MD',
	'me' => 'ME',
	'mg' => 'MG',
	'mh' => 'MH',
	'mk' => 'MK',
	'ml' => 'ML',
	'mm' => 'MM',
	'mn' => 'MN',
	'mo' => 'MO',
	'mp' => 'MP',
	'mq' => 'MQ',
	'mr' => 'MR',
	'ms' => 'MS',
	'mt' => 'MT',
	'mu' => 'MU',
	'mv' => 'MV',
	'mw' => 'MW',
	'mx' => 'MX',
	'my' => 'MY',
	'mz' => 'MZ',
	'na' => 'NA',
	'nc' => 'NC',
	'ne' => 'NE',
	'nf' => 'NF',
	'ng' => 'NG',
	'ni' => 'NI',
	'nl' => 'NL',
	'no' => 'NO',
	'np' => 'NP',
	'nr' => 'NR',
	'nu' => 'NU',
	'nz' => 'NZ',
	'om' => 'OM',
	'pa' => 'PA',
	'pe' => 'PE',
	'pf' => 'PF',
	'pg' => 'PG',
	'ph' => 'PH',
	'pk' => 'PK',
	'pl' => 'PL',
	'pm' => 'PM',
	'pn' => 'PN',
	'pr' => 'PR',
	'ps' => 'PS',
	'pt' => 'PT',
	'pw' => 'PW',
	'py' => 'PY',
	'qa' => 'QA',
	're' => 'RE',
	'ro' => 'RO',
	'rs' => 'RS',
	'ru' => 'RU',
	'rw' => 'RW',
	'sa' => 'SA',
	'sb' => 'SB',
	'sc' => 'SC',
	'sd' => 'SD',
	'se' => 'SE',
	'sf' => 'SF',
	'sg' => 'SG',
	'sh' => 'SH',
	'si' => 'SI',
	'sj' => 'SJ',
	'sk' => 'SK',
	'sl' => 'SL',
	'sm' => 'SM',
	'sn' => 'SN',
	'so' => 'SO',
	'sr' => 'SR',
	'st' => 'ST',
	'sv' => 'SV',
	'sy' => 'SY',
	'sz' => 'SZ',
	'tc' => 'TC',
	'td' => 'TD',
	'tf' => 'TF',
	'tg' => 'TG',
	'th' => 'TH',
	'tj' => 'TJ',
	'tk' => 'TK',
	'tl' => 'TL',
	'tm' => 'TM',
	'tn' => 'TN',
	'to' => 'TO',
	'tp' => 'TP',
	'tr' => 'TR',
	'tt' => 'TT',
	'tv' => 'TV',
	'tw' => 'TW',
	'tz' => 'TZ',
	'ua' => 'UA',
	'ug' => 'UG',
	'um' => 'UM',
	'us' => 'US',
	'uy' => 'UY',
	'uz' => 'UZ',
	'va' => 'VA',
	'vc' => 'VC',
	've' => 'VE',
	'vg' => 'VG',
	'vi' => 'VI',
	'vn' => 'VN',
	'vu' => 'VU',
	'wf' => 'WF',
	'wl' => 'WL',
	'ws' => 'WS',
	'ye' => 'YE',
	'yt' => 'YT',
	'za' => 'ZA',
	'zm' => 'ZM',
	'zw' => 'ZW'
);

/* DEFAULT IMAGES */
$tb_default_images = array(
	'player' => get_bloginfo('template_directory').'/images/defaults/player.jpg',
	'player_thumb' => get_bloginfo('template_directory').'/images/defaults/player-thumb.jpg',
	'crest-large' => get_bloginfo('template_directory').'/images/defaults/crest-large.png',
	'featured' => get_bloginfo('template_directory').'/images/defaults/featured.jpg',
	'rotator' => get_bloginfo('template_directory').'/images/defaults/rotator.jpg'
);

foreach( $tb_option_fields as $optiongroupkey => $optiongroup ) {
	foreach( $optiongroup as $key => $value ) {
		if ( get_option( $key ) === false )
			update_option( $key, $value );
	}
}

foreach( $tb_customize_colors as $color ) {
	if ( get_option( $color['slug'] ) === false ) 
		update_option( $color['slug'], $color['default'] );
}

?>